# Generated by Django 5.1.3 on 2024-11-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_questionlike_app_questio_user_id_a178c0_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
